name: flutter_sharez
description: ""
version: 2.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  alfred: ^1.1.1
  auto_route: ^11.1.0
  bonsoir: ^6.0.2
  crypto: ^3.0.7
  dart_jwt_token: ^0.0.3
  dart_mappable: ^4.3.0
  device_preview: ^1.2.0
  device_preview_screenshot: ^1.0.0
  dio: ^5.9.2
  dio_smart_retry: ^7.0.1
  duration: ^4.0.3
  file_picker: ^10.3.10
  file_sizes: ^1.0.6
  flash: ^3.1.1
  flex_color_scheme: ^8.0.2
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_displaymode: ^0.7.0
  flutter_form_builder: ^10.2.0
  flutter_localizations:
    sdk: flutter
  flutter_markdown_plus: ^1.0.7
  flutter_native_splash: ^2.4.4
  flutter_riverpod: ^3.3.1
  flutter_secure_storage_x: ^12.1.5+0
  flutter_speed_dial: ^7.0.0
  hive_ce_flutter: ^2.2.0
  hive_flutter: ^1.1.0
  internet_connection_checker_plus: ^2.6.0
  intl: ^0.20.2
  lottie: ^3.3.0
  lucide_icons: ^0.257.0
  multiple_result: ^5.1.0
  network_discovery: ^1.0.0
  open_filex: ^4.6.0
  package_info_plus: ^9.0.0
  path: ^1.8.3
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  platform_info: ^5.0.0
  qr_flutter: ^4.1.0
  receive_sharing_intent: ^1.8.1
  responsive_framework:
    git: https://github.com/Shreemanarjun/ResponsiveFramework.git
  rhttp: ^0.15.1
  riverpod: ^3.2.1
  shadcn_ui: ^0.52.1
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_web_socket: ^3.0.0
  slang: ^4.4.0
  slang_flutter: ^4.4.0
  talker_dio_logger: ^5.1.15
  talker_flutter: ^5.1.15
  talker_riverpod_logger: ^5.1.14
  tray_manager: ^0.5.2
  url_launcher: ^6.3.1
  uuid: ^4.5.3
  web_socket_channel: ^3.0.3
  window_manager: ^0.5.1


dev_dependencies:
  auto_route_generator: ^10.5.0
  build_runner: ^2.13.0
  dart_mappable_builder: ^4.7.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  icons_launcher: ^3.0.0
  mocktail: ^1.0.4
  slang_build_runner: ^4.4.0
  spot: ^0.18.0
  very_good_analysis: ^10.2.0






flutter:
  uses-material-design: true
  assets:
    - assets/images/logo/
    - assets/anim/


