name: Flutter Workflow

on:
  pull_request:
    branches:
      - main
      - master
  push:
    tags:
      - 'v*'
      - 'V*'

permissions: read-all

jobs:
  build-and-release:
    # 🔒 SECURITY GUARD: Use self-hosted ONLY if the build is safe (same repo push or internal pull request).
    runs-on: ${{ (github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository)) && 'self-hosted' || 'ubuntu-latest' }}
    
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java (Only on GitHub Runners)
        if: "!contains(runner.labels, 'self-hosted')"
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter (Only on GitHub Runners)
        if: "!contains(runner.labels, 'self-hosted')"
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Clean build artifacts
        run: flutter clean

      - name: Solve dependencies
        run: flutter pub get

      - name: Run unit tests
        run: flutter test --coverage

      - name: Build APKs
        run: |
          flutter build apk --release
          flutter build apk --split-per-abi

      - id: read-version
        uses: NiklasLehnfeld/flutter-version-number-action@main
        with:
          file-path: pubspec.yaml

      - name: Push to Releases
        # 🛡️ ONLY RUNS IF THE EVENT IS A TAG PUSH STARTING WITH v or V
        if: startsWith(github.ref, 'refs/tags/v') || startsWith(github.ref, 'refs/tags/V')
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/*.apk"
          tag: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
